Models/ErrorViewModel.cs
namespace MVC_P11_EsmeraldaGarcía.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/cursos.cs
using System.ComponentModel.DataAnnotations;

namespace MVC_P11_EsmeraldaGarcía.Models
{
    public class cursos
    {
        [Key]
        public int? id_cursos { get; set; }
        public string? nombre { get; set; }
    }
}

Models/dato.cs
using System.ComponentModel.DataAnnotations;

namespace MVC_P11_EsmeraldaGarcía.Models
{
    public class dato
    {
        [Key]

        public int? id_dato { get; set; }
        public string? name_user { get; set; }
        public string? password { get; set; }
        public string? genero { get; set; }
        public string? direction { get; set; }
        public string? pasatiempo { get; set; }
        public string? id_cursos { get; set; }
        public string? conocimientos { get; set; }

    }
}

Models/datoContext.cs
using Microsoft.EntityFrameworkCore;

namespace MVC_P11_EsmeraldaGarcía.Models
{
    public class datoContext  : DbContext
    {
        public datoContext(DbContextOptions<datoContext> options) : base(options)
        {


        }
        public DbSet<cursos> cursos { get; set; }
        public DbSet<dato> dato { get; set; }
    }
}

Controllers/HomeController.cs
using Firebase.Auth;
using Firebase.Storage;
using Microsoft.AspNetCore.Mvc;
using MVC_P11_EsmeraldaGarcía.Models;
using System.Diagnostics;

namespace MVC_P11_EsmeraldaGarcía.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public  async Task<ActionResult> SubirArchivo(IFormFile archivo)
        {
            //Leemos el archivo subido
            Stream archivoASubir = archivo.OpenReadStream();

            //ConfigurationRoot la conexion hacia FareBase
            string email = "esmeralda.garcia1@catolica.edu.sv"; /*Correo para autenticar en FireBase*/
            string clave = "abril2024";     //Contraseña establecida en ela auticacion en FireBase
            string ruta = "mvcp11esmeraldagarcia.appspot.com";   // URL donde se guardaran los arhivos
            string api_key = "AIzaSyBgLO7IwDKSEs6X-9DydDr7LtxN9ztwRqQ";  //API_KEY indentificador del proyecto en FireBase

            var auth = new FirebaseAuthProvider(new FirebaseConfig(api_key));

            var autenticarFireBase = await auth.SignInWithEmailAndPasswordAsync(email, clave);

            var cancellation = new CancellationTokenSource();
            var tokenUser = autenticarFireBase.FirebaseToken;

            var tareaCargarArchivo = new FirebaseStorage(ruta,
                new FirebaseStorageOptions
                {
                    AuthTokenAsyncFactory = () => Task.FromResult(tokenUser),
                    ThrowOnCancel = true
                }).Child("Archivos")
                .Child(archivo.FileName)
                .PutAsync(archivoASubir, cancellation.Token);

            var urlArchivoCargado = await tareaCargarArchivo;

            return RedirectToAction("Index");
        }
    }
}

Controllers/datossController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_P11_EsmeraldaGarcía.Models;

namespace MVC_P11_EsmeraldaGarcía.Controllers
{
    public class datossController : Controller
    {
        
        public IActionResult Index()
        {
            //Para mostrar en la tabka
            var listadodedato = (from e in _datoContext.dato
                                 select new
                                 {
                                     Nombre = e.name_user,
                                     Descripcion = e.direction,
                                     Genero = e.genero,
                                     Cursos = e.id_cursos,
                                     Pasatiempo = e.pasatiempo
                                 }).ToList();
            ViewData["listadodedato"] = listadodedato;
            return View();
        }
        public IActionResult Crear(dato nuevodato)
        {   
              //Crear y guardar los nuevos datos
            _datoContext.Add(nuevodato);
            _datoContext.SaveChanges();

            //retorna al index
            return RedirectToAction("Index");
        }



        private readonly datoContext _datoContext;
        public datossController(datoContext datoContext)
        {
            _datoContext = datoContext;
        }

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>



    @* AGREGAR ARCHIVO A FIREBASE *@
      <form asp-action="SubirArchivo" method="post" enctype="multipart/form-data">
        <div class="form-group mt-4">
            <label for="archivo">Seleccione el archivo a cargar</label>
            <input type="file" class="form-control" id="archivo" name="archivo" />


            <button type="submit" class="btn btn-primary mb-2 mt-4">Subir Archivo</button>

        </div>
      
      </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_P11_EsmeraldaGarcía</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_P11_EsmeraldaGarcía.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_P11_EsmeraldaGarcía</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="datoss" asp-action="Index">Datos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVC_P11_EsmeraldaGarcía - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/datoss/Index.cshtml
<h1> DATOS</h1>
</br>
<form asp-action="Crear">
    <div class=" form-group row mb-4">
        
        @* NOMBRE *@
        <div class="row mt-3">
            <lable>
                       Nombre
            </lable>
            <div class="col-sm-4">
                @Html.TextBox("name_user", "", new { @class = "form-control" })
            </div>

        </div>

        @* FIN NOMBRE *@

        @* CONTRASENA *@
        <div class="row mt-3">
            <lable>
                Password
            </lable>
            <div class="col-sm-4">
                @Html.Password("password", "", new { @class = "form-control" })
            </div>
        </div>
        @* FIN CONTRASENA *@

        @* GENERO *@
        <div class="row mt-3">
            <lable>
                Genero
            </lable>
            <div class="col-sm-4">
                @Html.RadioButton("genero", "Masculino", false, new { id = "id_dato" })
                Masculino
                @Html.RadioButton("genero", "Femenino", false, new { id = "id_dato" })
                Femenino
            </div>
        </div>
        @* FIN GENERO *@

        @* DIRECCION *@
        <div class="row mt-3">
            <lable>
                Direccion 
            </lable>
            <div class="col-sm-4">
                @Html.TextArea("direction",
                         new { @class = "form-control", @placeHolder = "Ingrese la descripción", id = "id_dato" })
            </div>
        </div>
        @* FIN DIRECCION *@

        @* PASATIEMPOS *@
        <div class="row mt-3">
            <lable>
                Pasatiempos
            </lable>
            <div class="col-sm-4">
                <label><input type="checkbox" name="pasatiempo" value="Bailar" /> Bailar</label>
                <label><input type="checkbox" name="pasatiempo" value="Correr" /> Correr</label>
                <label><input type="checkbox" name="pasatiempo" value="Escalar" /> Escalar</label>
                <label><input type="checkbox" name="pasatiempo" value="Peliculas" /> Películas</label>
            </div>
        </div>
            @* FIN PASARTIEMPOS *@

            @* CURSOS *@
        <div class="row mt-3">
            <lable>
                Cursos
            </lable>
            <div class="col-sm-4">
                <select name ="id_cursos" id="id_dato" >
                    <option value="">---Seleccione Curso---</option>
                    <option selected="selected">POO</option>
                    <option>DAW</option>
                    <option>MICRO</option>
                    <option>SI</option>
                    <option>REDES</option>

                </select>
            </div>
        </div>
        @* FIN CURSOS *@

        @* HABILIDADES *@
        <div class="row mt-3">
            <lable>
                Habilidades
            </lable>
            <div class="col-sm-4">
                <select name="conocimientos" id="id_dato">
                    <option value="1">C#</option>
                    <option value="2">ASP.NET</option>
                    <option value="2">JAVA</option>


               

                </select>
            </div>
        </div>
        @* FIN HABILIDADES *@


        @*BTN GUARDADO*@
        <div class="form-group row mb-4">
            <div class="col-sm-2">
            </div>
            <div class="col-sm-4" style="margin-top: 20px;">
                <input type="submit" class="btn-primary" value="Guardar" />
            </div>
        </div>
        @* FIN BTN GUARDADO*@

        @* INICIO TABLA *@
        <table class="table table-sm">
            <thead>
                <tr class="text-md-center">
                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th>Genero</th>
                    <th>Cursos</th>
                    <th>Pasatiempos</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var dato in (IEnumerable<dynamic>)ViewData["listadodedato"])
                {
                    <tr>
                        <td>@dato.Nombre</td>
                        <td>@dato.Descripcion</td>
                        <td>@dato.Genero</td>
                        <td>@dato.Cursos</td>
                        <td>@dato.Pasatiempo</td>
                    </tr>

                }
            </tbody>
        </table>
        @* FIN TABLA*@




    </div>
</form>